services:
  web:
    build: .
    container_name: blog-web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres@db:5432/blogdb
      - SECRET_KEY=dev-secret
      - CLOUDINARY_CLOUD_NAME=qtcyxptv
      - CLOUDINARY_API_KEY=637946757755496
      - CLOUDINARY_API_SECRET=hh2MrNprGvGILJUvC-rxCw1qbio
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    container_name: blog-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blogdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: