[project]
name = "blog-api"
version = "0.1.0"
description = "Blog API profesional con FastAPI"
requires-python = ">=3.11"
dependencies = [
    "aiofiles",
    "aiosqlite",
    "alembic",
    "annotated-doc",
    "annotated-types",
    "anyio",
    "asyncpg",
    "bcrypt==4.0.1",
    "certifi",
    "cffi",
    "click",
    "cloudinary",
    "colorama",
    "cryptography",
    "deprecated",
    "dnspython",
    "ecdsa",
    "email-validator",
    "fastapi",
    "greenlet",
    "h11",
    "httptools",
    "idna",
    "limits",
    "mako",
    "markupsafe",
    "packaging",
    "passlib",
    "pyasn1",
    "pycparser",
    "pydantic",
    "pydantic-core",
    "pydantic-settings",
    "python-dotenv",
    "python-jose",
    "python-multipart",
    "pyyaml",
    "rsa",
    "six",
    "slowapi",
    "sqlalchemy",
    "starlette",
    "typing-extensions",
    "typing-inspection",
    "urllib3",
    "uvicorn",
    "watchfiles",
    "websockets",
    "wrapt",
]

[project.optional-dependencies]
dev = [
    "coverage",
    "httpcore",
    "httpx",
    "iniconfig",
    "pluggy",
    "pygments",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
]
