"""add_cover_image_to_post

Revision ID: 411c281c813b
Revises: 59d5917d3ffe
Create Date: 2026-07-16 14:05:16.078171

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "411c281c813b"
down_revision: str | Sequence[str] | None = "59d5917d3ffe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("cover_image", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "cover_image")
    # ### end Alembic commands ###
